import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "./_components/ThemeProvider";

const manrope = Manrope({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
